// src/lib/components/Projects.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { onMount } from 'svelte';

	let sectionRef: HTMLElement;
	let visible = $state(false);
	let activeTab = $state<'sites' | 'bots' | 'plugins' | 'api'>('sites');

	interface Project {
		name: string;
		description: string;
		accentColor: string;
		stack: string[];
		url: string;
	}

	const sites: Project[] = [
		{
			name: 'FLW',
			description: 'Мой личный Minecraft проект - полнофункциональный сайт с онлайн картой, вики, системой управления и интеграцией с игровым сервером.',
			accentColor: '#60a5fa',
			stack: ['TypeScript', 'Next.js', 'React', 'Bun'],
			url: 'https://flowerymc.online/'
		},
		{
			name: 'Затмение',
			description: 'Веб-платформа для Minecraft проекта с современным дизайном и функциональностью.',
			accentColor: '#a855f7',
			stack: ['TypeScript', 'Next.js', 'React'],
			url: 'https://zatmenie.space/'
		},
		{
			name: 'MoernCordd',
			description: 'Современный веб-проект с уникальным дизайном и функциональностью.',
			accentColor: '#f97316',
			stack: ['TypeScript', 'Next.js', 'React', 'Tailwind'],
			url: 'https://moerncordd.vercel.app/'
		},
		{
			name: 'RGB Community',
			description: 'Сайт для RGB сообщества с интерактивными элементами.',
			accentColor: '#ec4899',
			stack: ['TypeScript', 'Next.js', 'React'],
			url: 'https://rgb-community.vercel.app/'
		},
		{
			name: 'OwlsVPN',
			description: 'Лендинг для VPN сервиса с современным UI/UX.',
			accentColor: '#22c55e',
			stack: ['TypeScript', 'Next.js', 'Tailwind'],
			url: 'https://owlsvpn.vercel.app/'
		},
		{
			name: 'Портфолио',
			description: 'Сайт моего портфолио с информацией о проектах, навыках и контактах.',
			accentColor: '#3b82f6',
			stack: ['TypeScript', 'Svelte', 'SvelteKit', 'Tailwind'],
			url: 'https://newermamalchik.space/'
		}
	];

	const bots: Project[] = [
		{
			name: 'FLW Bot',
			description: 'Многофункциональный Discord бот для проекта FLW. Работает с сервером, получает данные о проекте и игроках.',
			accentColor: '#5865f2',
			stack: ['TypeScript', 'Discord.js', 'Bun'],
			url: '#'
		}
	];

	const plugins: Project[] = [
		{
			name: 'FLW Core',
			description: 'Основной плагин для Minecraft сервера FLW. Ядро системы с API для других плагинов.',
			accentColor: '#22c55e',
			stack: ['Java', 'Paper API', 'MySQL'],
			url: '#'
		}
	];

	const apis: Project[] = [
		{
			name: 'API Личного кабинета',
			description: 'API для личного кабинета на сайте FLW. Авторизация, управление профилем и интеграция с игровым сервером.',
			accentColor: '#10b981',
			stack: ['TypeScript', 'Bun', 'Elysia', 'PostgreSQL'],
			url: '#'
		},
		{
			name: 'API Комментариев и лайков',
			description: 'API для системы комментариев и лайков. Модерация контента и уведомления.',
			accentColor: '#ec4899',
			stack: ['TypeScript', 'Bun', 'PostgreSQL'],
			url: '#'
		},
		{
			name: 'API Постов и ленты',
			description: 'API для публикации постов и формирования ленты новостей.',
			accentColor: '#8b5cf6',
			stack: ['TypeScript', 'Bun', 'PostgreSQL', 'Redis'],
			url: '#'
		},
		{
			name: 'API Городов',
			description: 'API для системы городов на сервере. Создание, управление и статистика.',
			accentColor: '#06b6d4',
			stack: ['TypeScript', 'Bun', 'PostgreSQL'],
			url: '#'
		},
		{
			name: 'API Загрузки картинок',
			description: 'API для загрузки и хранения изображений в ленту и профили.',
			accentColor: '#f97316',
			stack: ['TypeScript', 'Bun', 'S3', 'Sharp'],
			url: '#'
		}
	];

	const tabs = [
		{ id: 'sites' as const, label: 'Сайты', icon: 'mingcute:laptop-line', count: sites.length },
		{ id: 'bots' as const, label: 'Боты', icon: 'mingcute:discord-line', count: bots.length },
		{ id: 'plugins' as const, label: 'Плагины', icon: 'mingcute:game-2-line', count: plugins.length },
		{ id: 'api' as const, label: 'API', icon: 'mingcute:api-line', count: apis.length }
	];

	const currentProjects = $derived(
		activeTab === 'sites' ? sites :
		activeTab === 'bots' ? bots :
		activeTab === 'plugins' ? plugins : apis
	);

	onMount(() => {
		const observer = new IntersectionObserver(
			(entries) => {
				entries.forEach((entry) => {
					if (entry.isIntersecting) {
						visible = true;
					}
				});
			},
			{ threshold: 0.1 }
		);

		if (sectionRef) {
			observer.observe(sectionRef);
		}

		return () => observer.disconnect();
	});
</script>

<section
	id="projects"
	bind:this={sectionRef}
	class="relative py-24 lg:py-32"
>
	<!-- Background -->
	<div class="absolute inset-0 h-full w-full grid-pattern z-5 opacity-40 mask-y-from-80"></div>

	<div class="px-8 lg:px-16 xl:px-24 relative z-50 {visible ? 'animate-fade-in-up' : 'opacity-0'}">

		<!-- Header - left aligned -->
		<div class="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6 mb-12">
			<div class="flex flex-col gap-3">
				<div class="flex items-center gap-3">
					<div class="w-10 h-10 rounded-xl bg-blue-500/15 flex items-center justify-center">
						<Icon icon="mingcute:box-3-line" class="text-blue-400" width="20" />
					</div>
					<h2 class="font-[family-name:var(--font-raleway)] font-bold text-white text-3xl lg:text-4xl">
						Проекты
					</h2>
				</div>
				<p class="font-[family-name:var(--font-zed)] text-white/50 text-[13px] max-w-lg">
					Веб-платформы, боты, плагины и API сервисы
				</p>
			</div>

			<!-- Tabs - inline on desktop -->
			<div class="flex gap-2 flex-wrap">
				{#each tabs as tab}
					<button
						onclick={() => activeTab = tab.id}
						class="flex gap-2 items-center px-3.5 py-2 rounded-lg smooth cursor-pointer {activeTab === tab.id ? 'bg-white/10 text-white' : 'text-white/50 hover:text-white hover:bg-white/5'}"
					>
						<Icon icon={tab.icon} width="14" />
						<span class="font-[family-name:var(--font-zed)] text-[12px]">{tab.label}</span>
						<span class="font-[family-name:var(--font-zed)] text-[10px] px-1.5 py-0.5 rounded bg-white/10">{tab.count}</span>
					</button>
				{/each}
			</div>
		</div>

		<!-- Projects list - vertical cards -->
		<div class="flex flex-col gap-4">
			{#each currentProjects as project, i (project.name)}
				<div
					class="group flex flex-col lg:flex-row lg:items-center gap-4 lg:gap-8 p-5 lg:p-6 rounded-2xl border border-white/8 hover:border-white/15 bg-white/3 hover:bg-white/5 smooth"
				>
					<!-- Color indicator + name -->
					<div class="flex items-center gap-4 lg:min-w-[200px]">
						<div
							class="w-3 h-3 rounded-full flex-shrink-0"
							style="background-color: {project.accentColor}"
						></div>
						<h3 class="font-[family-name:var(--font-raleway)] font-semibold text-white text-[17px]">
							{project.name}
						</h3>
					</div>

					<!-- Description -->
					<p class="font-[family-name:var(--font-zed)] text-white/60 text-[13px] leading-relaxed flex-1">
						{project.description}
					</p>

					<!-- Stack tags -->
					<div class="flex flex-wrap gap-1.5 lg:min-w-[180px]">
						{#each project.stack.slice(0, 3) as tech}
							<span class="px-2 py-0.5 rounded text-[10px] font-[family-name:var(--font-zed)] bg-white/5 text-white/50">
								{tech}
							</span>
						{/each}
						{#if project.stack.length > 3}
							<span class="px-2 py-0.5 rounded text-[10px] font-[family-name:var(--font-zed)] bg-white/5 text-white/30">
								+{project.stack.length - 3}
							</span>
						{/if}
					</div>

					<!-- Link button -->
					{#if project.url !== '#'}
						<a
							href={project.url}
							target="_blank"
							class="flex gap-2 items-center px-4 py-2 rounded-lg border border-white/10 hover:border-white/25 hover:bg-white/5 smooth lg:ml-auto"
						>
							<Icon icon="mingcute:external-link-line" class="text-white/60" width="14" />
							<span class="font-[family-name:var(--font-zed)] text-white/80 text-[12px]">Открыть</span>
						</a>
					{:else}
						<div class="flex gap-2 items-center px-4 py-2 rounded-lg border border-white/5 lg:ml-auto">
							<Icon icon="mingcute:lock-line" class="text-white/30" width="14" />
							<span class="font-[family-name:var(--font-zed)] text-white/30 text-[12px]">Приватный</span>
						</div>
					{/if}
				</div>
			{/each}
		</div>
	</div>
</section>

// components/Projects.tsx
'use client'

import { useState } from 'react'
import React from 'react'
import { BoxIcon, ArrowRightIcon, LaptopIcon, ServerIcon, GearIcon, TypeScriptIcon, ReactIcon, NextJSIcon, TailwindIcon, BunIcon, PostgreSQLIcon, RedisIcon, JavaScriptIcon, DiscordIcon } from './Icons'

interface Project {
  name: string
  domain: string
  year: string
  description: string
  accentColor: string
  stack: string[]
  url: string
  type: 'site' | 'other'
  image?: string
  backgroundImage?: string
}

const sites: Project[] = [
  {
    name: 'FLW',
    domain: 'flowerymc.online',
    year: '2025-2026',
    description: 'Мой личный Minecraft проект - полнофункциональный сайт с онлайн картой, вики, системой управления и интеграцией с игровым сервером.',
    accentColor: '#60a5fa',
    stack: ['TypeScript', 'Next.js', 'React', 'Bun'],
    url: 'https://flowerymc.online/',
    type: 'site',
    image: 'https://flowerymc.online/shamewall/1.png',
    backgroundImage: '/image1.png',
  },
  {
    name: 'Затмение',
    domain: 'zatmenie.space',
    year: '2025-2026',
    description: 'Веб-платформа для Minecraft проекта с современным дизайном и функциональностью.',
    accentColor: '#a855f7',
    stack: ['TypeScript', 'Next.js', 'React'],
    url: 'https://zatmenie.space/',
    type: 'site',
    image: 'https://zatmenie.space/zatmenie/zatmenie.svg',
    backgroundImage: '/image.png',
  },
  {
    name: 'Портфолио',
    domain: 'neweramamalchik.space',
    year: '2025-2026',
    description: 'Сайт моего портфолио с информацией о проектах, навыках и контактах.',
    accentColor: '#3b82f6',
    stack: ['TypeScript', 'Next.js', 'React', 'Tailwind CSS'],
    url: 'https://neweramamalchik.space/',
    type: 'site',
    backgroundImage: '/image2.png',
  },
]

const other: Project[] = [
  {
    name: 'Discord Bot FLW',
    domain: 'discord-bot',
    year: '2025-2026',
    description: 'Многофункциональный Discord бот для проекта FLW. Работает с сервером, получает данные о проекте и игроках. Может подсказать что есть на сервере и чего нету, предоставляет полезную информацию игрокам.',
    accentColor: '#a855f7',
    stack: ['TypeScript', 'JavaScript', 'Discord.js', 'Bun'],
    url: '#',
    type: 'other',
  },
  {
    name: 'API для ЛК FLW',
    domain: 'api-lk',
    year: '2025-2026',
    description: 'API для личного кабинета на сайте FLW. Обеспечивает авторизацию, управление профилем и интеграцию с игровым сервером.',
    accentColor: '#10b981',
    stack: ['TypeScript', 'Bun', 'PostgreSQL'],
    url: '#',
    type: 'other',
  },
  {
    name: 'API Новостей FLW',
    domain: 'api-news',
    year: '2025-2026',
    description: 'Отдельный API для загрузки и управления новостями проекта. Позволяет добавлять, редактировать и получать новости через RESTful интерфейс.',
    accentColor: '#3b82f6',
    stack: ['TypeScript', 'Bun', 'PostgreSQL'],
    url: '#',
    type: 'other',
  },
  {
    name: 'API Игроков FLW',
    domain: 'api-players',
    year: '2025-2026',
    description: 'API для получения списка всех игроков, их статистики и данных. Интеграция с игровым сервером для получения актуальной информации об игроках.',
    accentColor: '#60a5fa',
    stack: ['TypeScript', 'Bun', 'PostgreSQL', 'Redis'],
    url: '#',
    type: 'other',
  },
  {
    name: 'API Админ-панели FLW',
    domain: 'api-admin',
    year: '2025-2026',
    description: 'API для управления проектом прямо с сайта через админ-панель. Позволяет управлять сервером, игроками, настройками и другими аспектами проекта.',
    accentColor: '#f59e0b',
    stack: ['TypeScript', 'Bun', 'PostgreSQL', 'Redis'],
    url: '#',
    type: 'other',
  },
]

const Projects = () => {
  const [activeTab, setActiveTab] = useState<'site' | 'other'>('site')

  // Функция для конвертации hex в rgba с прозрачностью
  const hexToRgba = (hex: string, alpha: number): string => {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    return `rgba(${r}, ${g}, ${b}, ${alpha})`
  }

  const getCurrentProjects = () => {
    switch (activeTab) {
      case 'site':
        return sites
      case 'other':
        return other
      default:
        return sites
    }
  }

  const getTabIcon = (tab: 'site' | 'other') => {
    switch (tab) {
      case 'site':
        return <LaptopIcon className="text-white" size={14} />
      case 'other':
        return <GearIcon className="text-white" size={14} />
    }
  }

  return (
    <div id="projects" className="flex flex-col px-4 sm:px-8 lg:px-24 relative mt-12 sm:mt-16 lg:mt-0 pb-8">
      <div className="absolute inset-0 h-full w-full bg-[radial-gradient(#171717_1.5px,transparent_1.5px)] [background-size:16px_16px] z-5 mask-y-from-80%"></div>

      <div className="translate-y-0 scale-100 opacity-100 blur-none flex flex-col z-50 smooth">
        <div className="flex flex-col items-start text-start gap-4 sm:gap-6 lg:gap-10">
          <div className="flex flex-col lg:flex-row items-start lg:items-center gap-4 sm:gap-6 lg:gap-8">
            <div className="flex items-center p-2 sm:p-3 rounded-xl bg-blue-700/10">
              <BoxIcon className="text-blue-100" size={20} />
            </div>
            <h1 className="text-white font-raleway font-semibold text-[32px] sm:text-[38px] md:text-[42px] lg:text-6xl leading-tight lg:leading-18">
              Мои <span className="text-blue-100 italic font-raleway tracking-tighter font-semibold inline-flex items-center gap-6">проекты</span>.
            </h1>
          </div>
          <p className="text-[12px] sm:text-[13px] lg:text-[14px] font-zed text-white/80 lg:max-w-4xl">
            Веб-платформы для Minecraft серверов, Discord боты и API для различных задач. 
            Создаю быстрые, надежные и масштабируемые решения с современным стеком технологий.
          </p>
          <div className="flex flex-col lg:flex-row gap-4 lg:items-center w-full lg:w-auto">
            <button
              onClick={() => setActiveTab('site')}
              className={`relative flex gap-2.5 items-center px-5 py-2.5 rounded-xl transition-all duration-300 ${
                activeTab === 'site' 
                  ? 'glass-liquid border border-blue-400/30 shadow-lg shadow-blue-400/10' 
                  : 'glass-effect border border-white/10 hover:border-white/20 hover:bg-white/5'
              }`}
            >
              {activeTab === 'site' && (
                <div className="absolute inset-0 bg-gradient-to-r from-blue-400/5 via-purple-400/5 to-blue-400/5 rounded-xl"></div>
              )}
              <div className="relative z-10">
                {getTabIcon('site')}
              </div>
              <p className={`relative z-10 font-zed text-[13px] font-medium transition-colors ${
                activeTab === 'site' ? 'text-white' : 'text-gray-400'
              }`}>
                Сайты
              </p>
            </button>
            <button
              onClick={() => setActiveTab('other')}
              className={`relative flex gap-2.5 items-center px-5 py-2.5 rounded-xl transition-all duration-300 ${
                activeTab === 'other' 
                  ? 'glass-liquid border border-purple-400/30 shadow-lg shadow-purple-400/10' 
                  : 'glass-effect border border-white/10 hover:border-white/20 hover:bg-white/5'
              }`}
            >
              {activeTab === 'other' && (
                <div className="absolute inset-0 bg-gradient-to-r from-purple-400/5 via-blue-400/5 to-purple-400/5 rounded-xl"></div>
              )}
              <div className="relative z-10">
                {getTabIcon('other')}
              </div>
              <p className={`relative z-10 font-zed text-[13px] font-medium transition-colors ${
                activeTab === 'other' ? 'text-white' : 'text-gray-400'
              }`}>
                Другое
              </p>
            </button>
          </div>
        </div>

        {/* Сетка проектов */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-6 mt-8 lg:mt-12">
          {getCurrentProjects().map((project, index) => {
            const isLastProject = index === getCurrentProjects().length - 1
            const isPortfolio = project.name === 'Портфолио'
            const showFooter = isLastProject && isPortfolio && activeTab === 'site'
            
            return (
              <React.Fragment key={index}>
                <div
                  className="group always-on-display flex flex-col rounded-3xl w-full relative overflow-hidden border border-white/10 backdrop-blur-xl"
              style={{
                background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0.02) 50%, rgba(255, 255, 255, 0.04) 100%)',
                backdropFilter: 'blur(20px) saturate(180%)',
                WebkitBackdropFilter: 'blur(20px) saturate(180%)',
              }}
            >
              {/* Фоновое изображение */}
              {project.backgroundImage && (
                <img 
                  src={project.backgroundImage}
                  alt={project.name}
                  className="absolute w-full h-full object-cover object-top top-0 left-0 z-0"
                  style={{
                    opacity: 0.35,
                  }}
                />
              )}

              {/* Декоративный градиент в углу */}
              <div 
                className="absolute top-0 right-0 w-32 h-32 opacity-10 blur-3xl"
                style={{
                  background: `radial-gradient(circle, ${project.accentColor}, transparent)`
                }}
              ></div>

              <div className="flex flex-col p-4 sm:p-5 lg:p-6 gap-3 sm:gap-4 relative z-10">
                {/* Заголовок с логотипом и названием */}
                <div className="flex items-start justify-between z-20 gap-3">
                  <div className="flex flex-col gap-2.5 flex-1 min-w-0">
                    <div className="flex gap-3 items-center z-20 flex-wrap">
                      <div className="relative flex-shrink-0">
                        {project.type === 'site' ? (
                          <>
                            {project.name === 'FLW' && project.image ? (
                              <div className="max-w-[120px] flex items-center justify-center relative">
                                <div className="absolute inset-0 bg-gradient-to-r from-blue-400/10 via-white/20 to-purple-400/10 rounded-lg blur-md scale-110 animate-pulse"></div>
                                <img 
                                  src={project.image}
                                  alt={project.name}
                                  className="z-[2] relative drop-shadow-lg h-12 w-auto object-contain"
                                  loading="lazy"
                                  onError={(e) => {
                                    const target = e.target as HTMLImageElement
                                    target.src = `https://www.google.com/s2/favicons?domain=${project.domain}&sz=64`
                                  }}
                                />
                              </div>
                            ) : (
                              <>
                                <img 
                                  src={project.image || `https://www.google.com/s2/favicons?domain=${project.domain}&sz=64`}
                                  alt={project.name}
                                  className="h-6 w-auto rounded-full"
                                  loading="lazy"
                                  onError={(e) => {
                                    const target = e.target as HTMLImageElement
                                    if (!project.image) {
                                      target.style.display = 'none'
                                      const parent = target.parentElement
                                      if (parent) {
                                        const fallback = document.createElement('div')
                                        fallback.className = 'h-6 w-6 rounded-full'
                                        fallback.style.backgroundColor = project.accentColor
                                        parent.appendChild(fallback)
                                      }
                                    } else {
                                      target.src = `https://www.google.com/s2/favicons?domain=${project.domain}&sz=64`
                                    }
                                  }}
                                />
                                <div className="ellipsis-animation absolute -top-3 -left-3">
                                  <div 
                                    className="size-12 rounded-full opacity-20 blur-[30px]"
                                    style={{ backgroundColor: project.accentColor }}
                                  ></div>
                                </div>
                              </>
                            )}
                          </>
                        ) : (
                          <div className="relative">
                            <div 
                              className="h-6 w-6 rounded-full"
                              style={{ backgroundColor: project.accentColor }}
                            ></div>
                            <div className="ellipsis-animation absolute -top-3 -left-3">
                              <div 
                                className="size-12 rounded-full opacity-20 blur-[30px]"
                                style={{ backgroundColor: project.accentColor }}
                              ></div>
                            </div>
                          </div>
                        )}
                      </div>
                      {project.name !== 'FLW' && (
                        <h1 className="font-raleway font-semibold text-white text-[18px] lg:text-[20px] leading-tight drop-shadow-lg" style={{ textShadow: '0 2px 8px rgba(0, 0, 0, 0.5)' }}>{project.name}</h1>
                      )}
                      <div 
                        className="px-2.5 py-1 rounded-full border"
                        style={{ 
                          backgroundColor: hexToRgba(project.accentColor, 0.15),
                          borderColor: hexToRgba(project.accentColor, 0.3)
                        }}
                      >
                        <h1 
                          className="font-zed font-bold text-[11px]"
                          style={{ color: project.accentColor }}
                        >
                          {project.year}
                        </h1>
                      </div>
                    </div>
                    <h1 className="font-zed font-medium text-gray-200 text-[12px] lg:text-[13px] drop-shadow-md" style={{ textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' }}>
                      {(() => {
                        const parts = project.domain.split('.')
                        if (parts.length > 1) {
                          const domainName = parts.slice(0, -1).join('.')
                          const domainZone = '.' + parts[parts.length - 1]
                          return (
                            <>
                              {domainName}
                              <span className="opacity-70 text-[12px] font-medium">{domainZone}</span>
                            </>
                          )
                        }
                        return project.domain
                      })()}
                    </h1>
                  </div>
                  <div className="hidden lg:flex gap-4 items-center flex-shrink-0">
                    <a 
                      href={project.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group/btn glass-liquid flex gap-2 items-center justify-center px-4 py-2 rounded-lg hover:scale-105 cursor-pointer transition-all duration-300 border border-white/15 hover:border-white/30 hover:shadow-lg"
                      style={{
                        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)'
                      }}
                    >
                      <ArrowRightIcon className="text-white group-hover/btn:translate-x-1 transition-transform duration-300" size={14} />
                      <p className="font-zed text-white text-[12px] font-semibold">Посмотреть</p>
                    </a>
                  </div>
                </div>

                {/* Тип проекта и описание */}
                <div className="flex flex-col gap-3.5 z-20">
                  <div className="flex gap-3 items-center">
                    {project.type === 'site' ? (
                      <>
                        <div className="flex gap-2 items-center">
                          <div 
                            className="flex p-1.5 rounded-lg border"
                            style={{ 
                              backgroundColor: hexToRgba(project.accentColor, 0.12),
                              borderColor: hexToRgba(project.accentColor, 0.2)
                            }}
                          >
                            <LaptopIcon 
                              className="text-lg"
                              style={{ color: project.accentColor }}
                              size={16}
                            />
                          </div>
                          <p className="font-zed text-white text-[12px] font-semibold drop-shadow-md" style={{ textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' }}>Фронтенд</p>
                        </div>
                        <span className="text-[11px] text-white/50">•</span>
                        <div className="flex gap-2 items-center">
                          <div 
                            className="flex p-1.5 rounded-lg border"
                            style={{ 
                              backgroundColor: hexToRgba(project.accentColor, 0.12),
                              borderColor: hexToRgba(project.accentColor, 0.2)
                            }}
                          >
                            <ServerIcon 
                              className="text-lg"
                              style={{ color: project.accentColor }}
                              size={16}
                            />
                          </div>
                          <p className="font-zed text-white text-[12px] font-semibold drop-shadow-md" style={{ textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' }}>Бекенд</p>
                        </div>
                      </>
                    ) : (
                      <div className="flex gap-2 items-center">
                        <div 
                          className="flex p-1.5 rounded-lg border"
                          style={{ 
                            backgroundColor: hexToRgba(project.accentColor, 0.12),
                            borderColor: hexToRgba(project.accentColor, 0.2)
                          }}
                        >
                          {project.name.includes('Discord') ? (
                            <GearIcon 
                              className="text-lg"
                              style={{ color: project.accentColor }}
                              size={16}
                            />
                          ) : (
                            <ServerIcon 
                              className="text-lg"
                              style={{ color: project.accentColor }}
                              size={16}
                            />
                          )}
                        </div>
                        <p className="font-zed text-white text-[12px] font-semibold drop-shadow-md" style={{ textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' }}>
                          {project.name.includes('Discord') ? 'Discord бот' : 'API'}
                        </p>
                      </div>
                    )}
                  </div>

                  <p className="font-zed text-gray-200 text-[12px] lg:text-[13px] max-w-xl text-pretty leading-relaxed drop-shadow-md" style={{ textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' }}>
                    {project.description}
                  </p>

                  {/* Технологии */}
                  <div className="flex flex-wrap gap-2 items-center z-20">
                    {project.stack.map((tech, techIndex) => {
                      // Функция для получения иконки технологии
                      const getTechIcon = (techName: string) => {
                        const techLower = techName.toLowerCase()
                        if (techLower.includes('typescript') || techLower === 'ts') {
                          return <TypeScriptIcon size={12} />
                        } else if (techLower.includes('react')) {
                          return <ReactIcon size={12} />
                        } else if (techLower.includes('next')) {
                          return <NextJSIcon size={12} />
                        } else if (techLower.includes('tailwind')) {
                          return <TailwindIcon size={12} />
                        } else if (techLower === 'bun') {
                          return <BunIcon size={12} />
                        } else if (techLower.includes('postgresql') || techLower.includes('postgres')) {
                          return <PostgreSQLIcon size={12} />
                        } else if (techLower === 'redis') {
                          return <RedisIcon size={12} />
                        } else if (techLower.includes('javascript') || techLower === 'js') {
                          return <JavaScriptIcon size={12} />
                        } else if (techLower.includes('discord')) {
                          return <DiscordIcon size={12} />
                        }
                        return null
                      }

                      const techIcon = getTechIcon(tech)
                      const techColor = project.accentColor

                      return (
                        <div key={techIndex} className="flex gap-2 items-center">
                          <div 
                            className="flex gap-2 items-center px-2.5 py-1 rounded-lg border"
                            style={{
                              backgroundColor: hexToRgba(techColor, 0.08),
                              borderColor: hexToRgba(techColor, 0.15)
                            }}
                          >
                            {techIcon && <span style={{ color: techColor }}>{techIcon}</span>}
                            <p 
                              className="font-zed text-[11px] font-medium drop-shadow-sm"
                              style={{ 
                                color: techColor,
                                textShadow: '0 1px 3px rgba(0, 0, 0, 0.3)'
                              }}
                            >
                              {tech}
                            </p>
                          </div>
                          {techIndex < project.stack.length - 1 && (
                            <span className="hidden lg:inline text-[10px] text-gray-500">•</span>
                          )}
                        </div>
                      )
                    })}
                  </div>

                  {/* Кнопка для мобильных */}
                  <a 
                    href={project.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group/btn glass-liquid flex gap-2 items-center justify-center px-4 py-2 rounded-lg hover:scale-105 cursor-pointer lg:hidden mt-2 transition-all duration-300 border border-white/15 hover:border-white/30 hover:shadow-lg"
                    style={{
                      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)'
                    }}
                  >
                    <ArrowRightIcon className="text-white group-hover/btn:translate-x-1 transition-transform duration-300" size={14} />
                    <p className="font-zed text-white text-[12px] font-semibold">Посмотреть</p>
                  </a>
                </div>
              </div>
            </div>
            {showFooter && (
              <div className="hidden lg:flex items-center justify-center">
                <footer className="flex flex-col gap-2 items-center justify-center">
                  <p className="font-zed text-gray-300 text-[12px] text-center">
                    Сделано <span className="gradient-text">с любовью</span>
                  </p>
                  <p className="font-zed text-gray-500/40 text-[9px] text-center opacity-30">
                    Идея портфолио взята у другого кодера
                  </p>
                </footer>
              </div>
            )}
            </React.Fragment>
            )
          })}
        </div>
      </div>
    </div>
  )
}

export default Projects
